name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9' 
          architecture: 'x64' 
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: pipenv install
      - name: Building exe
        run: pipenv run pyinstaller --onefile main.py --name rocketchat_postmessage_cli
